### ISSUE TITLE
Slug is not being auto-generated

### ISSUE THREAD

**Issue by Marketionist** [aldryn/aldryn-jobs#130]
**Steps to reproduce**
1. Go to "Job categories" or "Job openings" in sidebar admin panel
2. Add a new category or opening
3. Fill in "Name" or "Title" field

**Actual result**
"Name" or "Title" field is filled, "Slug" field is empty

**Expected result**
"Name" or "Title" field is filled, "Slug" field is auto-generated from "Name" or "Title"

**Comment by Marketionist** [comment]
**Update**
Please note that "Slug" field is being auto-generated (if the Save button is clicked, new entry with auto-generated slug is created), but it is not displayed while "Name" or "Title" fields are being filled

So, looks like front-end issue

**Comment by mkoistinen** [comment]
Not an issue, as designed. Won't fix.
