### ISSUE TITLE
JobOffer class is incorrectly named

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-jobs#56]
It should be ``Vacancy`` - a job offer is what you get get when you successfully apply for a vacancy; then you receive the offer.

It will be a real pain to migrate this, but I think it's worth it because it's so confusing that the main model in the application, not to mention all the text strings, relations and more, refer to something completely different.

Your thoughts?

**Comment by mkoistinen** [comment]
Agreed.

**Comment by intellectronica** [comment]
+1

**Comment by evildmp** [comment]
In that case I'll assume we're going with ``Vacancy`` and continue with the documentation accordingly.

If there are no existing users of this application who will need to migrate, do we even need to create a proper migration? Let's just start from scratch with them.

**Comment by mkoistinen** [comment]
We used Job Opening throughout.
