### ISSUE TITLE
"lead_in" field is inconsistent with names in other Addons

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-jobs#58]
Different Addons use different names for the same field, with no very good reason.

News & Blog, Jobs: ``lead_in``
Events, People: ``short_description``

``short_description`` is a much better name.

**Comment by mkoistinen** [comment]
Agreed.

**Comment by evildmp** [comment]
In that case I'll assume we're going with ``short_description`` and continue with the documentation accordingly.

**Comment by mkoistinen** [comment]
I've re-labeled the field "short description", but it is still lead_in in the model declaration. Closing.
