### ISSUE TITLE
Review app_config fields on JobApplication and JobOffer

### ISSUE THREAD

**Issue by mkoistinen** [aldryn/aldryn-jobs#59]
Since a JobApplication can only ever be "attached" to a single JobOffer (vacancy) and JobOffer already has a field "app_config", do we really need the same field on JobApplication?

Similarly, since a JobOffer is already attached to a *single* category, which, via its 1-to-1 companion model JobCategoryOpts already has a FK to JobsConfig, does it need its own FK to JobsConfig?

Sincere questions. Does anyone see the purpose in them?

For reference:

![image](https://cloud.githubusercontent.com/assets/615759/8609175/4482c44c-2670-11e5-9a50-e9aa1b43387c.png)

**Comment by cyberstar** [comment]
I vote for removing them, since I cannot find sense in managing them additionally.
Also for quick access to app_config shortcut method (property) can be created.

**Comment by mkoistinen** [comment]
Agreed.

**Comment by mkoistinen** [comment]
Closed, for reference, this is *now* the state of the models:

![20150712 aldryn jobs db schema](https://cloud.githubusercontent.com/assets/615759/8636558/18f6c742-2837-11e5-94ba-538e2574f4ed.jpg)
