### ISSUE TITLE
User needs more information in Form for Newsletter admin

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-jobs#67]
Something along the lines "Select the group(s) of users who should be informed when a visitor signs up for newsletters"

  <img width="683" alt="screenshot 2015-07-10 17 54 37" src="https://cloud.githubusercontent.com/assets/86222/8624030/e3a7f120-272c-11e5-8ac5-f5c3ab767dc7.png">

**Comment by mkoistinen** [comment]
To be closed by #83

**Comment by mkoistinen** [comment]
Closed by #83
