### ISSUE TITLE
What is the value of NewsletterSignup?

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-jobs#69]
``NewsletterSignup`` has a strong smell of being something that belongs not to a generic Jobs application, but to a particular client's requirements.

All it actually does is collect lists of email addresses.

There are all kinds of things that you might want to allow your visitors to provide their email addresses for, but there's no reason why it should specifically be for receiving newsletters, and no reason why it should apply specifically to Jobs (rather than events or news or whatever as well).

I'd simply strip this out of the application, and later provide incorporate it into a generic application that makes this functionality available for any purpose.

**Comment by mkoistinen** [comment]
To be closed by #83

**Comment by mkoistinen** [comment]
Closed by #83
