### ISSUE TITLE
Sometimes a Jobs List plugin is <empty>

### ISSUE THREAD

**Issue by evildmp** [aldryn/aldryn-jobs#78]
* create a ``Job opening`` (was: ``Job offer``)
* add a Job List plugin to a page:
  * select the apphook config
  * select the ``Job opening`` from the list

Should look like:

<img width="371" alt="screenshot 2015-07-13 16 46 39" src="https://cloud.githubusercontent.com/assets/86222/8653865/d1b04a9a-297e-11e5-933c-3feea4c8b849.png">

* Hit **Save**.

You'll get:

<img width="256" alt="screenshot 2015-07-13 16 47 51" src="https://cloud.githubusercontent.com/assets/86222/8654029/9ceb05c4-297f-11e5-8379-8acd22e575da.png">

If you save the plugin with only the apphook config set, it will subsequently work, even if you do select a job opening to display, but it won't remain selected next time you open the plugin for editing.

**Comment by mkoistinen** [comment]
Closed by #85
